mqtt:
  image: ansi/mosquitto
  container_name: mosquitto
  ports:
    - 1883:1883
  entrypoint: /usr/local/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
  volumes:
    - ./etc/mosquitto:/etc/mosquitto:ro
    - ./var/log/mosquitto:/var/log/mosquitto:rw

